### ISSUE TITLE
TickDB Naming Collision

### ISSUE THREAD

**Issue by ryanrussell** [clickingbuttons/tickdb#1]
Hey, 

Love the direction on what you're doing as discussed over discord.

Just a heads up, you have a naming collision with a Go lib. May want to consider options given you're still really early...

![image](https://user-images.githubusercontent.com/523300/165338955-7733eac9-1c96-4ebb-9bef-46e78b3b1aa5.png)

**Comment by clickingbuttons** [comment]
I like competition. Let's do better than @vimrus.
